export type ImportModule =
  | "vendors"
  | "transactions"
  | "sales"
  | "product_delivery_received"
  | "purchase_requisitions"
  | "purchase_orders"

export const IMPORT_MODULES: ImportModule[] = [
  "vendors",
  "transactions",
  "sales",
  "product_delivery_received",
  "purchase_requisitions",
  "purchase_orders",
]

const TEMPLATE_HEADERS: Record<ImportModule, string[]> = {
  vendors: [
    "vendor_code",
    "vendor_name",
    "mailing_address",
    "website",
    "phone",
    "email",
    "description",
    "bank_name",
    "bank_account_number",
    "bank_account_name",
    "bank_branch",
    "bank_routing_number",
    "bank_swift_code",
    "materials",
    "is_active",
  ],
  transactions: [
    "voucher_type",
    "date",
    "amount",
    "project_name",
    "project_id",
    "expense_head_name",
    "expense_head_code",
    "expense_head_id",
    "bank_account_title",
    "bank_account_id",
    "bill_no",
    "particulars",
    "is_confirmed",
    "vendor_name",
    "vendor_id",
    "reference_party_type",
    "reference_party_name",
    "dr_expense_head_name",
    "dr_expense_head_code",
    "dr_expense_head_id",
    "cr_expense_head_name",
    "cr_expense_head_code",
    "cr_expense_head_id",
    "dr_amount",
    "cr_amount",
  ],
  sales: [
    "sale_no",
    "sale_date",
    "booking_date",
    "customer_name",
    "customer_phone",
    "customer_id",
    "project_name",
    "project_id",
    "product_name",
    "unit_no",
    "product_id",
    "base_price",
    "discount_amount",
    "net_price",
    "booking_amount",
    "down_payment",
    "payment_plan",
    "sale_status",
    "notes",
  ],
  product_delivery_received: [
    "delivery_number",
    "po_number",
    "po_id",
    "vendor_name",
    "vendor_id",
    "vendor_code",
    "project_name",
    "project_id",
    "delivery_date",
    "received_date",
    "material_type",
    "material_specification",
    "delivered_qty",
    "accepted_qty",
    "rejected_qty",
    "unit_of_measurement",
    "delivery_status",
    "quality_status",
    "remarks",
  ],
  purchase_requisitions: [
    "mpr_no",
    "project_name",
    "project_id",
    "employee_name",
    "employee_id",
    "requisition_date",
    "required_date",
    "purpose_description",
    "expense_head_name",
    "expense_head_code",
    "expense_head_id",
    "description",
    "qty",
    "rate",
    "is_confirmed",
  ],
  purchase_orders: [
    "po_number",
    "vendor_name",
    "vendor_id",
    "vendor_code",
    "project_name",
    "project_id",
    "order_date",
    "expected_delivery_date",
    "status",
    "expense_head_name",
    "expense_head_code",
    "expense_head_id",
    "description",
    "qty",
    "unit_of_measurement",
    "rate",
    "payment_terms",
    "delivery_terms",
    "notes",
  ],
}

const TEMPLATE_SAMPLE_ROW: Record<ImportModule, string[]> = {
  vendors: [
    "V1001",
    "ABC Trading Company",
    "123 Main Street, Dhaka 1000, Bangladesh",
    "www.abctrading.com",
    "01700000000",
    "info@abctrading.com",
    "Cement and material supplier",
    "Dhaka Bank",
    "1234567890",
    "ABC Trading",
    "Banani Branch",
    "123456",
    "DHAKABD",
    "Cement, Sand, Steel",
    "true",
  ],
  transactions: [
    "Debit",
    "2026-04-01",
    "25000",
    "Main Project",
    "",
    "Material Expense",
    "4001",
    "",
    "Main Cash",
    "",
    "BILL-101",
    "Bulk imported transaction",
    "true",
    "ABC Trading",
    "",
    "VENDOR",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  sales: [
    "SALE-2026-0001",
    "2026-04-01",
    "2026-04-01",
    "Rahim Uddin",
    "01700000000",
    "",
    "Main Project",
    "",
    "Apt-2B",
    "2B",
    "",
    "5000000",
    "50000",
    "4950000",
    "200000",
    "300000",
    "installment",
    "booked",
    "Imported from legacy ERP",
  ],
  product_delivery_received: [
    "DEL-2026-0001",
    "PO-2026-0001",
    "",
    "ABC Traders",
    "",
    "V1001",
    "Main Project",
    "",
    "2026-04-02",
    "2026-04-02",
    "Cement",
    "Portland Cement 50kg",
    "100",
    "100",
    "0",
    "BAG",
    "Received",
    "Passed",
    "Imported delivery",
  ],
  purchase_requisitions: [
    "MPR000123",
    "Main Project",
    "",
    "Store Manager",
    "",
    "2026-04-01",
    "2026-04-05",
    "Site material requirement",
    "Material Expense",
    "4001",
    "",
    "Cement bags",
    "100",
    "550",
    "false",
  ],
  purchase_orders: [
    "PO-2026-0001",
    "ABC Traders",
    "",
    "V1001",
    "Main Project",
    "",
    "2026-04-01",
    "2026-04-05",
    "Draft",
    "Material Expense",
    "4001",
    "",
    "Cement bags",
    "100",
    "BAG",
    "550",
    "30% Advance",
    "On site delivery",
    "Imported purchase order",
  ],
}

export function getTemplateCsv(moduleName: ImportModule): string {
  const headers = TEMPLATE_HEADERS[moduleName]
  const sample = TEMPLATE_SAMPLE_ROW[moduleName]
  const lines = [headers.join(","), sample.join(",")]
  return lines.join("\n")
}

export function isImportModule(value: string): value is ImportModule {
  return IMPORT_MODULES.includes(value as ImportModule)
}
